Add saturation mode for fully compliant OFP8 E3M4 format
north-numerical-computing/cpfloat pull request #10
Opened 2024-05-30 18:57 UTC by mfasi

2024-05-31 08:35 UTC, mmikaitis requested changes
Max, looks good! I left a few minor comments.

2024-05-31 08:35 UTC, mmikaitis commented on mex/cpfloat.c
> +    fpopts->subnormal = CPFLOAT_SAT_NO;
fptops->subnormal set twice. The above instance was probably mean as fpopts->saturation.

2024-05-31 08:35 UTC, mmikaitis commented on mex/cpfloat.c
> +          fpopts->saturation = CPFLOAT_SAT_USE; /* Default for E4M3. */
E4M3 of OCP standard can operate in both sat and non-sat modes, but in non-sat mode overflows need to produce NaN. Saturation does not appear to be default.

2024-05-31 08:35 UTC, mmikaitis commented on mex/cpfloat.m
> +%     'E4M3' and 1 otherwise.
Saturation should be off by default and NaN should be produced instead of infinities unless users turn it on, I think.

2024-05-31 08:35 UTC, mmikaitis commented on test/cpfloat_test.m
> +  options.subnormal
Probably used for debugging and not required.

2024-05-31 15:42 UTC, mfasi commented on mex/cpfloat.c
> +    fpopts->subnormal = CPFLOAT_SAT_NO;
Good spot, thanks!

2024-05-31 15:45 UTC, mfasi commented on mex/cpfloat.c
> +          fpopts->saturation = CPFLOAT_SAT_USE; /* Default for E4M3. */
Formats without infinities is a separate step, but I'll make it default for E4M3 (only).

Should we then keep saturation mode off by default for all formats, including E4M3?

Either way, I would keep this change as is for now, as it will be easier to switch off infinities for this specific format.

2024-05-31 15:45 UTC, mfasi commented on test/cpfloat_test.m
> +  options.subnormal
Good catch!

2024-05-31 21:30 UTC, mfasi commented on mex/cpfloat.m
> +%     'E4M3' and 1 otherwise.
I've switched off saturation for all supported formats.

2024-06-01 07:15 UTC, mfasi commented on mex/cpfloat.c
> +          fpopts->saturation = CPFLOAT_SAT_USE; /* Default for E4M3. */
I've implemented support for infinities as a separate option, which is on by default for all formats but `E4M3` in the MEX interface. Saturation is now off by default for all formats.

2024-06-01 13:11 UTC, mmikaitis commented
Max, this looks good to me for main. Feel free to merge if you are happy with the changes.

2024-06-01 21:02 UTC, mfasi commented
Thanks! I'll add some tests and, if everything goes well, merge.

2024-06-02 07:06 UTC, merged